Add eslint check to CI

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -22,6 +22,13 @@ jobs:
             echo "Prettier check failed."
             exit 1
           fi
+      - name: Run ESlint
+        run: |
+          npm run lint
+          if [ $? -ne 0 ]; then
+            echo "ESlint failed."
+            exit 1
+          fi
 
   build:
     runs-on: ubuntu-latest
