Add prettier to CI

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,6 +3,26 @@ name: Test
 on: [push]
 
 jobs:
+  prettier-check:
+    runs-on: ubuntu-latest
+    env:
+      NODE_VERSION: 16.x
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Node.js ${{ env.NODE_VERSION }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ env.NODE_VERSION }}
+      - name: Install dependencies
+        run: npm ci
+      - name: Run Prettier Check
+        run: |
+          npm run lint-prettier
+          if [ $? -ne 0 ]; then
+            echo "Prettier check failed."
+            exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
 
@@ -18,7 +38,7 @@ jobs:
     #       - 27017:27017
 
     steps:
-      - uses: actions/checkout@v1
+      - uses: actions/checkout@v3
       - name: Start mongod
         shell: bash
         run: |
@@ -26,7 +46,7 @@ jobs:
           sleep 5s
           docker exec mongo /bin/bash -c "echo \"rs.initiate();\" | mongo"
       - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
       - name: Use NPM 7
